<?php

echo "autoload - Загружаем файл autoload.php перед тестами.\n";

// autoload.php @generated by Composer
// Регистрация процедуры автозагрузки классов во время выполнения тестов


// spl_autoload_register(function ($class) {
//     $prefix = 'Svr\\Raw\\';
//     $base_dir = __DIR__ . '/src/';
//     $len = strlen($prefix);
//     if (strncmp($prefix, $class, $len) !== 0) {
//         return;
//     }
//     $relative_class = substr($class, $len);
//     $file = $base_dir . str_replace('\\', '/', $relative_class) . '.php';
//     if (file_exists($file)) {
//         require $file;
//     }
// });